name: Learn GitHub Actions
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a simple command
        run: echo "Hello, GitHub Actions!"